spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa1dvclz4wwjsANN5d6
            client-secret: oelPx1HZYGXNuEA3MGZQAuS292_-ZE-Hscy60s9X
            client-name: okta
            redirect-uri: http://localhost:8081/ui-one/login/oauth2/code/custom
          custom:
            client-id: login-app
            client-secret: keyClock@#12345
            scope: email,profile
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/ui-one/login/oauth2/code/custom
            client-name: keyclock
        provider:
          okta:
            issuer-uri: https://dev-4482561.okta.com/oauth2/default
          custom:
            authorization-uri: http://localhost:8080/auth/realms/SpringBootKeyClock/protocol/openid-connect/auth
            token-uri: http://localhost:8080/auth/realms/SpringBootKeyClock/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/auth/realms/SpringBootKeyClock/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8081
  servlet: 
    context-path: /ui-one
    
logging: 
  level: 
    org.springframework: INFO

resourceserver:
  api:
    url: http://localhost:8084/sso-resource-server/api/foos/
              
