server: 
  port: 8084
  servlet: 
    context-path: /sso-resource-server


####### resource server configuration properties
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/SpringBootKeyClock
          jwk-set-uri: http://localhost:8080/auth/realms/SpringBootKeyClock/protocol/openid-connect/certs
  h2:
    console:
      enabled: true